log:
  level: INFO

entryPoints:
  websecure:
    address: "1.2.3.4:443"

providers:
  file:
    filename: "/usr/local/etc/traefik/traefik.yaml"

certificatesResolvers:
  le:
    acme:
      storage: "/usr/local/etc/traefik/acme.json"
      email: admin@example.com
      tlsChallenge: {}

tls:
  options:
    default:
      minVersion: VersionTLS13

http:
  middlewares:
    piler_headers:
      headers:
        customResponseHeaders:
          Server: ""
          Strict-Transport-Security: "max-age=31536000"
          X-Content-Type-Optionsi: "nosniff"
          Referrer-Policy: "same-origin"
  routers:
    piler:
      rule: "Host(`archive.example.com`)"
      service: piler
      middlewares:
        - "piler_headers"
      tls:
        certResolver: le
  services:
    piler:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:80/"
